version: '3.7'

services:
  schedule_db:
    restart: always
    container_name: schedule_db
    image: postgres:15.0-alpine
    volumes:
      - schedule_db_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  fast_api:
    restart: always
    container_name: schedule_fast_api
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head
      && gunicorn src.presentation.api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - schedule_db
      - rabbitmq
    volumes:
      - fast_api_media_volume:/usr/src/presentation/api/media
    env_file:
      - ./.env.docker

volumes:
  schedule_db_data:
  fast_api_media_volume:
  rabbitmq-data:
