"""remove inventarization

Revision ID: 079f34ce8dae
Revises: 92b172412b10
Create Date: 2025-01-31 14:58:09.616508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079f34ce8dae'
down_revision: Union[str, None] = '92b172412b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('consumable')
    op.drop_table('consumable_to_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumable_to_service',
    sa.Column('consumable_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumable.id'], name='consumable_to_inventory_consumable_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='consumable_to_inventory_service_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consumable_id', 'service_id', name='consumable_to_inventory_pkey')
    )
    op.create_table('consumable',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('count >= 0', name='check_count_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name='consumable_inventory_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='consumable_pkey')
    )
    op.create_table('inventory',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stock_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey')
    )
    # ### end Alembic commands ###
