"""add order photos

Revision ID: 11da64d95278
Revises: 19e7eaee3868
Create Date: 2024-12-10 19:45:40.730432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file.types

# revision identifiers, used by Alembic.
revision: str = '11da64d95278'
down_revision: Union[str, None] = '19e7eaee3868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('photo_before', sqlalchemy_file.types.ImageField(), nullable=True))
    op.add_column('order', sa.Column('photo_after', sqlalchemy_file.types.ImageField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'photo_after')
    op.drop_column('order', 'photo_before')
    # ### end Alembic commands ###
