"""refactoring relation between order and slot

Revision ID: c468e632af2a
Revises: 2c7267c34803
Create Date: 2025-02-10 10:53:04.031984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c468e632af2a'
down_revision: Union[str, None] = '2c7267c34803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('order_slot_id_key', 'order', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_slot_id_key', 'order', ['slot_id'])
    op.alter_column('order', 'status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
