"""remove link to other model service

Revision ID: 5332e903d0ae
Revises: 7cdd15e6e362
Create Date: 2025-03-26 12:02:43.913173

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5332e903d0ae"
down_revision: Union[str, None] = "7cdd15e6e362"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("promotion_to_service_service_id_fkey", "promotion_to_service", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "promotion_to_service_service_id_fkey",
        "promotion_to_service",
        "service",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
