"""add order payment table

Revision ID: 7cdd15e6e362
Revises: c468e632af2a
Create Date: 2025-02-27 15:35:06.282421

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cdd15e6e362"
down_revision: Union[str, None] = "c468e632af2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_payment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("point_uses", sa.Integer(), nullable=False),
        sa.Column("promotion_sale", sa.Integer(), nullable=False),
        sa.Column("is_payed", sa.Boolean(), server_default="f", nullable=False),
        sa.CheckConstraint("point_uses >= 0", name="check_point_uses_positive"),
        sa.CheckConstraint("promotion_sale >= 0", name="check_promotion_sale_positive"),
        sa.CheckConstraint("total_amount > 0", name="check_total_amount_positive"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_payment")
    # ### end Alembic commands ###
