"""chande order date to datetim

Revision ID: 92b172412b10
Revises: 11da64d95278
Create Date: 2024-12-19 17:30:12.637434

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92b172412b10"
down_revision: Union[str, None] = "11da64d95278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order", "date_add", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order", "date_add", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=False)
    # ### end Alembic commands ###
